name: Publish Preview
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: checkout-master
        uses: actions/checkout@v2
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: website
          CLEAN: true      
      - name: checkout-gh-pages
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
      - name: add-preview
        uses: actions/checkout@v2
        with:
          find: '<title>SPDX License List'
          replace: '<title>PREVIEW - SPDX License List'
      - name: fix-breadcrumbs
        uses: actions/checkout@v2
        with:
          find: '<a href="/">Home</a> » <a href="/licenses">Licenses</a>'
          replace: '<a href="/license-list-data">Licenses</a>'