name: Publish Preview
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: checkout-master
        uses: actions/checkout@v2
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: website
          CLEAN: true